### ISSUE TITLE
Outages Summary API not returning data for country

### ISSUE THREAD

**Issue by JayWebz** [CAIDA/ioda-api#28]
I think something is acting up with the outages summary api, something like https://api.ioda.caida.org/v2/outages/summary/region/?from=1608255424&until=1608341823&limit=10&includeMetadata=true is returning the region list just fine (as returns fine too) but change to country and nothing returns https://api.ioda.caida.org/v2/outages/summary/country/?from=1608255424&until=1608341823&limit=10&includeMetadata=true

**Comment by digizeph** [comment]
The country-level link works for me.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/659667/102923557-cb0ca300-4444-11eb-94a9-96b5e916e54e.png">

**Comment by digizeph** [comment]
@JayWebz can you confirm that this issue is resolved on your side? Thanks

**Comment by JayWebz** [comment]
Odd, yeah it's returning now. Not sure if it was just temporarily down or something.
